server:
  port: 8088
sharding:
  jdbc:
    datasource:
      names: master
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver # 使用新版本驱动，则要指定区时serverTimezone
        jdbc-url: jdbc:mysql://localhost:3306/mypratice?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&serverTimezone=Asia/Shanghai&&allowPublicKeyRetrieval=true
        username: root
        password: 123456
    # 水平拆分的数据库（表） 配置分库 + 分表策略 行表达式分片策略
    # 分库策略
    config:
      sharding:
        tables:
          inv_transaction:
            actual-data-nodes: master.inv_transaction_$->{0..2}
            table-strategy:
              inline:
                sharding-column: inv_transactions_id
                algorithm-expression: inv_transaction_$->{inv_transactions_id %3} # 分片算法表达式
            key-generator-column-name: inv_transactions_id
      #打印执行的数据库以及语句
      props:
        sql:
          show: true

spring:
  main:
    allow-bean-definition-overriding: true
#指定mybatis信息

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.shardingSphere.entity
#日志打印
logging:
  level:
    root: info
    org.springframework.web: info
    com.lucifer.sharding.dao: debug
    druid.sql: debug
